by_food:
    path: /food/{value}
    controller: App\Infrastructure\Controller\SearchBeerController::getByFood
    methods: [GET]

by_food_detail:
  path: /food/detail/{value}
  controller: App\Infrastructure\Controller\SearchBeerController::getByFoodDetail
  methods: [GET]