by_food:
    path: /food/{value}
    controller: App\Infrastructure\Controller\SearchBeerController::getByFood
    methods: [GET]

beer_detail:
  path: /show/{id}
  controller: App\Infrastructure\Controller\ShowBeerController::show
  methods: [GET]
  requirements:
    id: \d+